# Generated by Django 3.2.9 on 2021-12-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.TextField(max_length=250)),
                ('dostepnosc', models.CharField(max_length=50)),
                ('rodzaj_suplementu', models.CharField(max_length=50)),
                ('pojemnosc_suplementu', models.CharField(max_length=50)),
            ],
        ),
    ]
