# Generated by Django 3.2.9 on 2021-12-10 20:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_supplement_cena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinia', models.TextField(default='Wpisz swoją opinię')),
                ('nota', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('suplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.supplement')),
            ],
        ),
    ]
