# Generated by Django 3.2.9 on 2022-02-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_ocena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Producent',
                'verbose_name_plural': 'Producenci',
            },
        ),
        migrations.AlterModelOptions(
            name='ocena',
            options={'verbose_name': 'Ocena', 'verbose_name_plural': 'Oceny'},
        ),
        migrations.AlterModelOptions(
            name='supplement',
            options={'verbose_name': 'Suplement', 'verbose_name_plural': 'Suplementy'},
        ),
        migrations.AlterField(
            model_name='ocena',
            name='suplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to='Main.supplement'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='producent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.producent'),
        ),
    ]
