# Generated by Django 3.2.9 on 2022-02-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20220217_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podkategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Podkategoria',
                'verbose_name_plural': 'Podkategoria',
            },
        ),
        migrations.AddField(
            model_name='kategoria',
            name='Podkategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.podkategoria'),
        ),
    ]
