# Generated by Django 3.2.9 on 2022-02-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20220217_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoria',
            name='podkategoria',
        ),
    ]
