# Generated by Django 3.2.9 on 2022-02-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20220222_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='foto',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foto',
            name='nazwa',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
