# Generated by Django 3.2.9 on 2022-06-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='opis',
            field=models.TextField(max_length=3500),
        ),
    ]
