# Generated by Django 3.2.9 on 2022-10-16 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0017_alter_supplement_opis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zamowione', models.BooleanField(default=False)),
                ('data_dodania', models.DateTimeField(auto_now=True)),
                ('data_zamowienia', models.DateTimeField(null=True)),
                ('produkt', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.supplement')),
            ],
        ),
        migrations.CreateModel(
            name='Zamwowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zamowione', models.BooleanField(default=False)),
                ('data_zamowienia', models.DateTimeField(auto_now=True)),
                ('elementy', models.ManyToManyField(to='Main.ElementZamowienia')),
                ('klient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
