# Generated by Django 3.2.9 on 2022-11-04 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_auto_20221016_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('zamowione', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('koszyk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='Main.koszyk')),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówienia',
            },
        ),
    ]
