# Generated by Django 3.2.9 on 2022-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_kodyrabatowe'),
    ]

    operations = [
        migrations.AddField(
            model_name='kodyrabatowe',
            name='procent',
            field=models.FloatField(default=0.9),
        ),
    ]
