# Generated by Django 3.2.9 on 2022-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_kodyrabatowe_procent'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='kwota',
            field=models.FloatField(default=100),
        ),
    ]
