# Generated by Django 3.2.9 on 2022-11-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_zamowienie_kwota'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='zrealizowane',
            field=models.BooleanField(default=False),
        ),
    ]
