# Generated by Django 3.2.9 on 2023-01-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_zamowienie_zrealizowane'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplement',
            new_name='Suplement',
        ),
    ]
