# Generated by Django 3.2.9 on 2023-01-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_rename_supplement_suplement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ocena',
        ),
    ]
